name: squadron_builder
description: Dart code generator for Squadron workers. Implement your worker service and let squadron_builder bridge the gap with Web Workers and Isolates!
version: 6.0.0
homepage: https://github.com/d-markey/squadron_builder
repository: https://github.com/d-markey/squadron_builder

environment:
  sdk: ^3.4.0

platforms:
  linux:
  windows:
  macos:

dependencies:
  squadron: ^6.0.0
  build:
  source_gen:
  analyzer:
  meta:

dev_dependencies:
  lints:
  test:
  build_runner:
  logger:
  cancelation_token:

dependency_overrides:
  squadron:
    git: https://github.com/d-markey/squadron

topics:
  - codegen
  - concurrency
  - isolate
  - multithread
  - web-worker

funding:
  - https://github.com/sponsors/d-markey
