name: squadron_builder
description: Dart code generator for Squadron workers. Implement your worker service and let squadron_builder bridge the gap with Web Workers and Isolates!
version: 2.3.1
homepage: https://github.com/d-markey/squadron_builder
repository: https://github.com/d-markey/squadron_builder

environment:
  sdk: ">=2.12.0 <4.0.0"

platforms:
  linux:
  windows:
  macos:

dependencies:
  squadron: ">=4.3.5 <6.0.0"
  build: ^2.3.1
  source_gen: ^1.3.1
  analyzer: ^5.11.1

dev_dependencies:
  lints: ^2.0.1
  test: ^1.24.2
  build_runner: ^2.3.3
