name: squadron_builder
description: Dart code generator for Squadron workers. Implement your worker service and let squadron_builder bridge the gap with Web Workers and Isolates!
version: 2.0.0
homepage: https://github.com/d-markey/squadron_builder
repository: https://github.com/d-markey/squadron_builder

environment:
  sdk: '>=2.13.0 <3.0.0'

platforms:
  linux:
  windows:
  macos:

dependencies:
  squadron: ^4.3.3
  build: ^2.3.1
  source_gen: ^1.2.7
  analyzer: ^5.2.0
  dart_style: ^2.0.0
  pub_semver: ^2.1.3

dev_dependencies:
  lints: ^2.0.1
  test: ^1.23.1
  build_runner: ^2.3.3
  async: ^2.10.0
