name: squadron_builder
description: Dart code generator for Squadron workers. Implement your worker service and let squadron_builder bridge the gap with Web Workers and Isolates!
version: 6.0.0
homepage: https://github.com/d-markey/squadron_builder
repository: https://github.com/d-markey/squadron_builder

environment:
  sdk: ^3.0.0

platforms:
  linux:
  windows:
  macos:

dependencies:
  squadron: ^6.0.0
  build: ^2.3.1
  source_gen: ^1.3.1
  analyzer: ">=5.11.1 <7.0.0"
  meta: ^1.8.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.2
  build_runner: ^2.3.3
  logger: ^2.1.0
  cancelation_token: ^1.1.0

dependency_overrides:
  squadron:
    git: https://github.com/d-markey/squadron

topics:
  - codegen
  - concurrency
  - isolate
  - multithread
  - web-worker

funding:
  - https://github.com/sponsors/d-markey
