name: squadron_builder
description: Dart code generator for Squadron workers. Implement your worker service and let squadron_builder bridge the gap with Web Workers and Isolates!
version: 0.7.0
homepage: https://github.com/d-markey/squadron_builder
repository: https://github.com/d-markey/squadron_builder

environment:
  sdk: '>=2.13.0 <3.0.0'

dependencies:
  squadron: ^4.2.0
  build: ^2.1.1
  source_gen: ^1.1.1
  analyzer: ^4.3.1

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
  build_runner: ^2.1.10
